FROM ubuntu

RUN apt update
#RUN apt install -y build-essential git rubber
#RUN apt install -y build-essential git texlive-latex-extra
RUN apt install -y build-essential git texlive
#RUN tlmgr init-usertree

ENTRYPOINT ["bash"]
